name: xmdp
base: core18
version: git
summary: An MDP clone using libxmp
description: |
  xmdp is a clone of the Future Crew MusicDiskPlayer (released in 1993 with
  the Journey 1/2 and Chaotic Mind musicdisks) using libxmp to render module
  data. Besides being a music disk player, it can also be used to play
  stand-alone module files.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: i386
  - build-on: arm64
  - build-on: armhf

apps:
  xmdp:
    command: xmdp
    plugs:
      - home
      - alsa
      - pulseaudio
      - x11
      - wayland
      - opengl
      - audio-playback
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
      LIBGL_DRIVERS_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri

parts:
  xmdp:
    source: .
    plugin: make
    artifacts: [xmdp]
    build-packages:
      - gcc
      - make
      - libsdl2-dev
      - libxmp-dev
      - libpulse-dev
    stage-packages:
      - libsdl2-2.0-0
      - libxmp4
      - libpulse0
      - libgl1
